name: arise_application
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  rename_app: ^1.6.6
  supabase_flutter: ^2.17.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/icon.png
    - assets/icons/icon_white.png
    - assets/logo.png
  fonts:
    - family: Geist
      fonts:
        - asset: assets/fonts/geist/Geist-Regular.ttf
          weight: 400
